using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json.Linq;
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator


namespace Capstone.Web.JsonHelper
{
  

        public class GeocodedWaypoint
        {
            public string geocoder_status;
            public string place_id;
            public string[] types;
        }

        public class Northeast
        {
            public double lat;
            public double lng;
        }

        public class Southwest
        {
            public double lat;
            public double lng;
        }

        public class Bounds
        {
            public Northeast northeast;
            public Southwest southwest;
        }

        public class Distance
        {
            public string text;
            public int value;
        }

        public class Duration
        {
            public string text;
            public int value;
        }

        public class EndLocation
        {
            public double lat;
            public double lng;
        }

        public class StartLocation
        {
            public double lat;
            public double lng;
        }

        public class Distance2
        {
            public string text;
            public int value;
        }

        public class Duration2
        {
            public string text;
            public int value;
        }

        public class EndLocation2
        {
            public double lat;
            public double lng;
        }

        public class Polyline
        {
            public string points;
        }

        public class StartLocation2
        {
            public double lat;
            public double lng;
        }

        public class Step
        {
            public Distance2 distance;
            public Duration2 duration;
            public EndLocation2 end_location;
            public string html_instructions;
            public Polyline polyline;
            public StartLocation2 start_location;
            public string travel_mode;
            public string maneuver;
        }

        public class Leg
        {
            public Distance distance;
            public Duration duration;
            public string end_address;
            public EndLocation end_location;
            public string start_address;
            public StartLocation start_location;
            public Step[] steps;
            public object[] traffic_speed_entry;
            public object[] via_waypoint;
        }

        public class OverviewPolyline
        {
            public string points;
        }

        public class Route
        {
            public Bounds bounds;
            public string copyrights;
            public Leg[] legs;
            public OverviewPolyline overview_polyline;
            public string summary;
            public object[] warnings;
            public int[] waypoint_order;
        }

        public class DirectionsHelper
        {
            public GeocodedWaypoint[] geocoded_waypoints;
            public Route[] routes;
            public string status;
        }

    }


